apiVersion: v1
kind: Service
metadata:
  name: aiback-service
spec:
  selector:
    app: aiback
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aifront-service
spec:
  selector:
    app: aifront
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
